name: CI
on:
  pull_request:
  push:

    # if (typeof process.env.TRAVIS_TAG === "string" && process.env.TRAVIS_TAG[0] === "v") {
    #   return process.env.TRAVIS_TAG.substring(1);
    # }
    # if (
    #   typeof process.env.TRAVIS_BRANCH === "string" &&
    #   (process.env.TRAVIS_BRANCH[0] === "#" || process.env.TRAVIS_BRANCH === "master")
    # ) {
    #   return process.env.TRAVIS_BRANCH.replace(/#/, "_");
    # }

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        id: dt-ref
        with:
          script: |
            core.debug(github.ref_name);
            console.log("test");
            console.log(github.ref_name);
            if (github.event_name === 'pull_request') {
              // core.exportVariable('DT_REF', github.ref);
            }
            else if (github.event_name === 'push' && github.ref_name.lastIndexOf("#") === 0) {
              core.exportVariable('DT_REF', github.ref_name.replace(/#/, '_'));
            }
      # - uses: docker/setup-buildx-action@v3
      #   name: Set up Docker Buildx
      # - uses: docker/login-action@v3
      #   name: Log in to GitHub Container Registry # is dit nog nodig met load: true ?
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo $DT_REF;
      # - uses: docker/build-push-action@v5
      #   name: Build and push Docker image
      #   with:
      #     load: true
      #     tags: ghcr.io/tfrijsewijk/dso-toolkit:latest
      #     context: .
      #     cache-from: ghcr.io/tfrijsewijk/dso-toolkit:latest
      #     cache-to: type=inline
      #     build-args: |
      #       CI
      #       DT_REF: ${{ github.ref }}
      # - uses: addnab/docker-run-action@v3
      #   name: Run Danger CI
      #   if: github.event_name == 'pull_request'
      #   with:
      #     registry: ghcr.io
      #     image: ghcr.io/tfrijsewijk/dso-toolkit:latest
      #     options:
      #       --env CI
      #       --env DT_REF=${{ github.ref }}
      #       # --env CI \
      #       # --env DANGER_GITHUB_API_TOKEN \
      #       # --env TRAVIS_PULL_REQUEST \
      #       # --env TRAVIS_REPO_SLUG \
      #       # --env TRAVIS_JOB_ID \
      #       # --env HAS_JOSH_K_SEAL_OF_APPROVAL \
      #     run: yarn danger ci
      # - uses: addnab/docker-run-action@v3
      #   name: Run e2e tests
      #   with:
      #     registry: ghcr.io
      #     image: ghcr.io/tfrijsewijk/dso-toolkit:latest
      #     options:
      #       --env CI
      #       --env DT_REF=${{ github.ref }}
      #       # --env TRAVIS_BRANCH \
      #       # --env TRAVIS_BUILD_ID \
      #       # --env TRAVIS_BUILD_NUMBER \
      #       # --env TRAVIS_COMMIT \
      #       # --env TRAVIS_PULL_REQUEST \
      #       # --env TRAVIS_PULL_REQUEST_BRANCH \
      #       # --volume /home/travis/build/dso-toolkit/dso-toolkit/storybook/cypress-parallel:/usr/src/app/storybook/cypress-parallel \
      #     run: yarn e2e
      # - uses: addnab/docker-run-action@v3
      #   name: Deploy
      #   with:
      #     registry: ghcr.io
      #     image: ghcr.io/tfrijsewijk/dso-toolkit:latest
      #     options:
      #       --env CI
      #       --env DT_REF=${{ github.ref }}
      #       # --env DT_PRIVATE_KEY_BASE64 \
      #       # --env DT_DEPLOY_HOST \
      #       # --env DT_DEPLOY_PORT \
      #       # --env DT_DEPLOY_USER \
      #       # --env DT_DEPLOY_ROOT \
      #       # --env DT_DEPLOY_NPM_TOKEN \
      #       # --env GH_TOKEN \
      #       # --env TRAVIS_BRANCH \
      #       # --env TRAVIS_TAG \
      #     run: bash deploy.sh
