name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/tfrijsewijk/dso-toolkit:latest
          context: .
          cache-from: ghcr.io/tfrijsewijk/dso-toolkit:latest
          cache-to: type=inline
          build-args: |
            CI
            DT_REF: ${{ github.ref }}
      - uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: tfrijsewijk/dso-toolkit:latest
          options: --env CI --env DT_REF=${{ github.ref }}
          run: bash deploy.sh
