name: Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - run: |
          BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$GITHUB_REF_NAME}
          TAG=${BRANCH/\#/}

          docker build \
          --target source \
          --cache-to type=inline \
          --cache-from ghcr.io/dso-toolkit/dso-toolkit:${TAG}-source \
          --cache-from ghcr.io/dso-toolkit/dso-toolkit:master-source \
          --tag ghcr.io/dso-toolkit/dso-toolkit:${TAG}-source \
          --progress plain \
          --build-arg CI \
          --build-arg TRAVIS_BRANCH=$GITHUB_REF_NAME \
          --build-arg TRAVIS_TAG \
          --pull \
          .
